demilich1/metastone

- cards/classic/priest/spell_shadowform.json
- cards/classic/rogue/spell_headcrack.json
- cards/classic/warlock/spell_bane_of_doom.json
- cards/classic/warlock/spell_mortal_coil.json
- cards/classic/warrior/spell_slam.json
- src/main/java/net/demilich/metastone/game/Attribute.java
- src/main/java/net/demilich/metastone/game/logic/GameLogic.java
- src/main/java/net/demilich/metastone/game/spells/ReturnMinionToHandSpell.java
- src/main/java/net/demilich/metastone/game/spells/SetHeroHpSpell.java
-Fixed death checking in Slam, Mortal Coil, Bane of Doom.
-Fixed hero healing to use a Hero's max HP and not the default max HP.
-Added setting a Hero's max HP to a higher setting if their base was not high enough (i.e. Alexstrasza on Ragnaros.)
-Fixed cards being returned to hand not being killed when their owner's hand is full.
-Fixed a bug with silence not setting minion's health correctly if its max HP was different from its base HP.
-Fixed a bug where Shadowform would give you Mind Shatter if you did not have the Priest starting Hero Power.
-Fixed a bug where Shadowforming twice in some circumstances could leave you with Mind Spike.
-Fixed a bug where Headcrack was being added to your hand immediately, instead of the end of your turn.
> Some minor bug fixes

- cards/classic/rogue/spell_betrayal.json
- src/test/java/net/demilich/metastone/tests/SpecialCardTests.java
Also added unit tests. This fixes issue #13.
> Fix betrayal spell to correctly use the custom class.

- cards/naxxramas/minion_webspinner.json
- src/main/java/net/demilich/metastone/game/cards/desc/SpellDeserializer.java
- src/main/java/net/demilich/metastone/game/logic/GameLogic.java
Let's not talk about what happened.
Webspinner is now a Beast.
Full Mana Crystals can now be given to players when ModifyMaxMana is
cast. (Fixes Nourish and Grove Tender that I know of)
> Fixed major bugs

- cards/classic/neutral/minion_harvest_golem.json
- cards/naxxramas/minion_webspinner.json
> Added missing "Race" attribute to Webspinner and Harvest Golem

- cards/blackrock_mountain/minion_majordomo_executus.json
- cards/classic/paladin/spell_lay_on_hands.json
Fixes mistakes in Majordomo Executus and Lay on Hands.
> Fixes #71 

- src/main/java/net/demilich/metastone/game/behaviour/GreedyOptimizeTurn.java
- src/main/java/net/demilich/metastone/game/behaviour/learning/Brain.java
- src/main/java/net/demilich/metastone/game/behaviour/learning/LearningBehaviour.java
- src/main/java/net/demilich/metastone/game/behaviour/mcts/MonteCarloTreeSearch.java
- src/main/java/net/demilich/metastone/game/spells/trigger/PreDamageTrigger.java
- src/main/java/net/demilich/metastone/gui/battleofdecks/BattleOfDecksResultView.java
- src/test/java/net/demilich/metastone/tests/BlackrockMountainTests.java
Unnecessary, yet useful thing to do. I hate warning.
> Commented unused code (Removes warnings).

- README.md
- build.gradle
- src/main/java/net/demilich/metastone/game/cards/CardParser.java
- src/test/java/net/demilich/metastone/tests/ValidateCards.java
- added a ValidateCards test to ensure that all cards are parseable
- updated Readme with Running Tests section
- note this PR depends on the gradle wrapper change in my previous PR
> adding ValidateCards test

- src/main/java/net/demilich/metastone/game/cards/HeroCard.java
- src/main/java/net/demilich/metastone/gui/gameconfig/PlayerConfigView.java
Removed UI dependency from HeroCard
* removed HeroCard.getImage() method along with imports of
javafx.scene.image.Image and net.demilich.metastone.gui.IconFactory
* updated PlayerConfigView.selectHero(HeroCard) to create the Image
inline rather than calling into HeroCard
* fixed HeroCard method parameter name to start with a lowercase
character
> Herocard image dependency

- src/main/java/net/demilich/metastone/game/Player.java
- src/main/java/net/demilich/metastone/game/behaviour/threat/cuckoo/WinRateFitness.java
- src/main/java/net/demilich/metastone/game/gameconfig/GameConfig.java
- src/main/java/net/demilich/metastone/game/gameconfig/PlayerConfig.java
- src/main/java/net/demilich/metastone/gui/battleofdecks/StartBattleOfDecksCommand.java
- src/main/java/net/demilich/metastone/gui/gameconfig/PlayerConfigView.java
- src/main/java/net/demilich/metastone/gui/playmode/StartGameCommand.java
- src/main/java/net/demilich/metastone/gui/playmode/config/PlayModeConfigMediator.java
- src/main/java/net/demilich/metastone/gui/playmode/config/PlayModeConfigView.java
- src/main/java/net/demilich/metastone/gui/sandboxmode/SandboxModeConfigView.java
- src/main/java/net/demilich/metastone/gui/sandboxmode/commands/CreateNewSandboxCommand.java
- src/main/java/net/demilich/metastone/gui/simulationmode/PlayerInfoView.java
- src/main/java/net/demilich/metastone/gui/simulationmode/SimulateGamesCommand.java
- src/main/java/net/demilich/metastone/gui/simulationmode/SimulationModeConfigView.java
- src/main/java/net/demilich/metastone/gui/simulationmode/SimulationResult.java
- src/main/java/net/demilich/metastone/gui/trainingmode/PerformTrainingCommand.java
- src/test/java/net/demilich/metastone/tests/CloningTest.java
- src/test/java/net/demilich/metastone/tests/MassTest.java
- src/test/java/net/demilich/metastone/tests/TestBase.java
- applied refactor operation to update all files where PlayerConfig and
GameConfig are used with the appropriate package name
> Moved GameConfig and PlayerConfig out of gui package and into game package

- src/main/java/net/demilich/metastone/game/decks/RandomDeck.java
- src/main/java/net/demilich/metastone/game/decks/validation/DefaultDeckValidator.java
- src/main/java/net/demilich/metastone/game/decks/validation/IDeckValidator.java
- src/main/java/net/demilich/metastone/gui/deckbuilder/DeckProxy.java
- specifically, moved the gui/deckbuilder/validation package into the game/decks package
- updated imports accordingly
> Moved DeckValidator classes into game package 

- formats/all.json
- formats/standard.json
- formats/wild.json
- src/main/java/net/demilich/metastone/game/cards/CardCatalogue.java
- src/main/java/net/demilich/metastone/game/cards/CardCollection.java
- src/main/java/net/demilich/metastone/game/cards/CardSet.java
- src/main/java/net/demilich/metastone/game/cards/CardType.java
- src/main/java/net/demilich/metastone/game/cards/Rarity.java
- src/main/java/net/demilich/metastone/game/decks/RandomDeck.java
- src/main/java/net/demilich/metastone/game/spells/desc/condition/CardPropertyCondition.java
- src/main/java/net/demilich/metastone/game/spells/desc/filter/CardFilter.java
- src/main/java/net/demilich/metastone/game/spells/trigger/CardPlayedTrigger.java
- src/main/java/net/demilich/metastone/game/spells/trigger/DamageCausedTrigger.java
- src/main/java/net/demilich/metastone/gui/sandboxmode/CardCollectionEditor.java
-Updated Enums to have all correct values.
-Included self-contained comparitors for CardType and Rarity.
-Fixes some Spell/Choose One issues.
> Updated CardSet, CardType, and Rarity Enums

- cards/classic/hunter/secret_misdirection.json
- cards/classic/warlock/spell_sense_demons.json
- cards/league_of_explorers/secret_sacred_trial.json
- cards/naxxramas/secret_avenge.json
- cards/reward/minion_captains_parrot.json
- cards/the_grand_tournament/paladin/secret_competitive_spirit.json
- cards/the_old_gods/neutral/minion_ancient_harbinger.json
- cards/the_old_gods/neutral/minion_deathwing_dragonlord.json
- cards/the_old_gods/shaman/minion_master_of_evolution.json
- src/main/java/net/demilich/metastone/game/spells/FromDeckToHandSpell.java
- src/main/java/net/demilich/metastone/game/spells/PutRandomMinionOnBoardSpell.java
- src/main/java/net/demilich/metastone/game/spells/TransformToRandomMinionSpell.java
- src/main/java/net/demilich/metastone/game/spells/desc/condition/IsDeadCondition.java
-Fixes #100 for sure this time. I think.
-Updated FromDeckToHandSpell
--Updated Captain's Parrot and Sense Demons to match change
--Added Ancient Harbinger
-Updated PutRandomMinionOnBoardSpell
--Added Deathwing, Dragonlord
-Replaced TransformRandomMinionToManaCostSpell to TransformToRandomMinionSpell
--Updated Recombobulator to match change
--Added Master of Evolution
> Small Spell Update

- app/src/main/java/net/demilich/metastone/gui/deckbuilder/ChooseClassView.java
- app/src/main/java/net/demilich/metastone/gui/deckbuilder/DeckBuilderMediator.java
- app/src/main/java/net/demilich/metastone/gui/deckbuilder/DeckInfoView.java
- app/src/main/java/net/demilich/metastone/gui/deckbuilder/DeckProxy.java
- app/src/main/java/net/demilich/metastone/gui/deckbuilder/SetActiveDeckCommand.java
- app/src/main/resources/fxml/ChooseClassView.fxml
- game/src/main/java/net/demilich/metastone/game/decks/Deck.java
- game/src/main/java/net/demilich/metastone/game/decks/validation/ArbitraryDeckValidator.java
- game/src/main/java/net/demilich/metastone/game/logic/GameLogic.java
- Added the ability to make and edit Arbitrary Decks. This includes 0 card decks, though it looks weird in game. Unfortunately, I'm having odd issues testing this on the merged copy, as I get inconsistent AppConfig/BuildConfig errors. Fixes #44 
EDIT: I got a copy working. It seems to work just fine.
> Added Arbitrary Deck Option

- cards/src/main/resources/cards/classic/rogue/minion_defias_ringleader.json
- cards/src/main/resources/cards/classic/rogue/minion_edwin_vancleef.json
- cards/src/main/resources/cards/classic/rogue/minion_kidnapper.json
- cards/src/main/resources/cards/classic/rogue/minion_si7_agent.json
- cards/src/main/resources/cards/classic/rogue/spell_eviscerate.json
- cards/src/main/resources/cards/classic/rogue/spell_headcrack.json
- cards/src/main/resources/cards/classic/rogue/weapon_perditions_blade.json
- cards/src/main/resources/cards/goblins_vs_gnomes/rogue/spell_sabotage.json
- cards/src/main/resources/cards/goblins_vs_gnomes/rogue/spell_tinkers_sharpsword_oil.json
- cards/src/main/resources/cards/the_grand_tournament/rogue/minion_shado-pan_rider.json
- cards/src/main/resources/cards/the_grand_tournament/rogue/minion_undercity_valiant.json
- cards/src/main/resources/cards/the_old_gods/rogue/minion_bladed_cultist.json
- game/src/main/java/net/demilich/metastone/game/cards/MinionCard.java
- game/src/main/java/net/demilich/metastone/game/cards/WeaponCard.java
- game/src/main/java/net/demilich/metastone/game/cards/costmodifier/CardCostModifier.java
- game/src/main/java/net/demilich/metastone/game/cards/desc/AttributeDeserializer.java
- game/src/main/java/net/demilich/metastone/game/spells/desc/filter/CardFilter.java
- game/src/main/java/net/demilich/metastone/game/spells/desc/valueprovider/AlgebraicOperation.java
- game/src/main/java/net/demilich/metastone/game/spells/desc/valueprovider/AlgebraicValueProvider.java
- game/src/main/java/net/demilich/metastone/game/utils/GameTagUtils.java
- Removed Silence Tag
- Added internal functions for Algebraic Operations
- Added COMBO attribute to Combo cards (Cards can now be filtered with
the COMBO Attribute.)
- Added default operator for CardFilter without an operation defined.
> Updated Game Tags

- app/src/main/java/net/demilich/metastone/MetaStone.java
An issue existed where the main bulk of graphics for the program would not appear on the screen. This was (partially) resolved by using a similar method to  the one suggested in the following Oracle forum post:
https://community.oracle.com/thread/3752935?start=0&tstart=0
Thanks to demilich1 for the suggestion.
> Fixing JavaFX Visual Bug

- cards/src/main/resources/cards/classic/mage/spell_cone_of_cold.json
- game/src/main/java/net/demilich/metastone/game/logic/GameLogic.java
- game/src/main/java/net/demilich/metastone/game/spells/AdjacentEffectSpell.java
- Fixed Adjacent Effect Spell
- Fixes #161 and #162
> Fixed Cone of Cold and Spellbender

- README.md
- app/src/main/java/net/demilich/metastone/gui/cards/CardProxy.java
- app/src/main/java/net/demilich/metastone/gui/deckbuilder/DeckProxy.java
- game/src/main/java/net/demilich/metastone/game/cards/CardCatalogue.java
- shared/src/main/java/net/demilich/metastone/utils/ResourceLoader.java
> Copy cards from cards.jar into user's home metastone/cards dir

- cards/src/main/resources/cards/classic/paladin/secret_redemption.json
- game/src/main/java/net/demilich/metastone/game/logic/GameLogic.java
- Fixed Redemption (Fixes #169)
- Fixed late Aura updates (Fixes #170)
> Fixed Redemption and Aura Updates

- game/src/main/java/net/demilich/metastone/game/spells/desc/filter/CardFilter.java
> Fixed Rarity Filter

- cards/src/main/resources/cards/goblins_vs_gnomes/rogue/minion_ogre_ninja.json
- cards/src/main/resources/cards/the_old_gods/hunter/minion_princess_huhuran.json
- cards/src/main/resources/cards/the_old_gods/neutral/minion_cyclopian_horror.json
- cards/src/main/resources/cards/the_old_gods/neutral/minion_eater_of_secrets.json
- cards/src/main/resources/cards/the_old_gods/neutral/minion_faceless_shambler.json
- cards/src/main/resources/cards/the_old_gods/neutral/minion_twilight_elder.json
-Fixed various card issues (fixes #192)
> Card Fixes

- .gitignore
- README.md
- shared/src/main/java/net/demilich/metastone/utils/UserHomeMetastone.java
- added code to UserHomeMetastone.java to check for ENV variable with key USER_HOME_METASTONE
- if its not null or empty then use that string as the path with which to initialize our UserHomeMetastone class
> adding ability to change the User's Home Metastone dir path with an ENV variable

- game/src/main/java/net/demilich/metastone/game/spells/DiscardSpell.java
- Discard Spell now allows the use of a Card Filter.
> Updated Discard Spell

- app/src/main/java/net/demilich/metastone/gui/gameconfig/PlayerConfigView.java
- game/src/main/java/net/demilich/metastone/game/decks/DeckFactory.java
- game/src/main/java/net/demilich/metastone/game/decks/RandomDeck.java
- game/src/test/java/net/demilich/metastone/tests/CloningTest.java
- game/src/test/java/net/demilich/metastone/tests/MassTest.java
- game/src/test/java/net/demilich/metastone/tests/TestBase.java
- Random Decks now take into account the Deck Format that is in use (Fixes #183)
> Fixed Random Decks

- cards/src/main/resources/cards/league_of_explorers/minion_summoning_stone.json
- cards/src/main/resources/cards/one_night_in_karazhan/minion_medivh_the_guardian.json
- cards/src/main/resources/cards/one_night_in_karazhan/minion_netherspite_historian.json
- cards/src/main/resources/cards/one_night_in_karazhan/minion_silverware_golem.json
- cards/src/main/resources/cards/one_night_in_karazhan/minion_zoobot.json
- cards/src/main/resources/cards/one_night_in_karazhan/weapon_atiesh.json
- Summoning Stone was tested and does NOT summon directly next to it. So weird...
> Added new cards and fixed Summoning Stone

- game/src/main/java/net/demilich/metastone/game/cards/CardCatalogue.java
> Fixed card version check

- cards/src/main/resources/cards/basic/druid/hero_malfurion.json
- cards/src/main/resources/cards/basic/hunter/hero_rexxar.json
- cards/src/main/resources/cards/basic/hunter/token_huffer.json
- cards/src/main/resources/cards/basic/hunter/token_misha.json
- cards/src/main/resources/cards/basic/mage/hero_jaina.json
- cards/src/main/resources/cards/basic/paladin/hero_uther.json
- cards/src/main/resources/cards/basic/priest/hero_anduin.json
- cards/src/main/resources/cards/basic/rogue/hero_valeera.json
- cards/src/main/resources/cards/basic/shaman/hero_thrall.json
- cards/src/main/resources/cards/basic/warlock/hero_guldan.json
- cards/src/main/resources/cards/basic/warrior/hero_garrosh.json
- cards/src/main/resources/cards/blackrock_mountain/hero_ragnaros.json
- cards/src/main/resources/cards/classic/hunter/token_hound.json
- cards/src/main/resources/cards/classic/warlock/hero_jaraxxus.json
- game/src/main/java/net/demilich/metastone/game/cards/CardCatalogue.java
- game/src/main/java/net/demilich/metastone/game/cards/CardParser.java
- Updated Card Parser to be awesomely efficient, as well as kick out cards that don't follow de rules.
- Fixed a few token cards that were missing descriptions.
- Added missing, but relatively useless, tags to hero cards.
> Card Parsing Update

- app/src/main/java/net/demilich/metastone/gui/sandboxmode/commands/PerformActionCommand.java
- game/src/main/java/net/demilich/metastone/game/GameContext.java
- game/src/main/java/net/demilich/metastone/game/cards/desc/ParseUtils.java
- game/src/main/java/net/demilich/metastone/game/logic/ActionLogic.java
- game/src/main/java/net/demilich/metastone/game/logic/GameLogic.java
- game/src/main/java/net/demilich/metastone/game/targeting/EntityReference.java
- game/src/main/java/net/demilich/metastone/game/targeting/TargetSelection.java
- Added Auto Hero Powers. Using AUTO for Target Selection will
automatically use the Hero Power if it could be cast.
- Added Leftmost minion targeting for friendly and enemy minions.
- Added Opposite minion targeting.
> Feature Update

- cards/src/main/resources/cards/one_night_in_karazhan/spell_ironforge_portal.json
- Fixed Ironforge Portal to be a Warrior card that costs 5. (Fixes #234)
> Fixed Ironforge Portal

- cards/src/main/resources/cards/classic/shaman/minion_unbound_elemental.json
- game/src/main/java/net/demilich/metastone/game/GameContext.java
- game/src/main/java/net/demilich/metastone/game/cards/costmodifier/CardCostModifier.java
- game/src/main/java/net/demilich/metastone/game/events/GameEvent.java
- game/src/main/java/net/demilich/metastone/game/logic/GameLogic.java
- game/src/main/java/net/demilich/metastone/game/spells/trigger/IGameEventListener.java
- game/src/main/java/net/demilich/metastone/game/spells/trigger/SpellTrigger.java
- game/src/main/java/net/demilich/metastone/game/spells/trigger/TriggerLayer.java
- game/src/main/java/net/demilich/metastone/game/spells/trigger/TriggerManager.java
- game/src/main/java/net/demilich/metastone/game/spells/trigger/secrets/Secret.java
- Triggers now function on the same layer for ALL abilities. (Fixes #240 as well as a bunch of hidden bugs)
- Fixed a bug where Unbound Elemental was not being buffed when Overload
cards were Countered.
> Removed Trigger Layers

- cards/src/main/resources/cards/classic/hunter/secret_freezing_trap.json
- cards/src/main/resources/cards/classic/rogue/spell_shadowstep.json
- cards/src/main/resources/cards/one_night_in_karazhan/minion_netherspite_historian.json
- cards/src/main/resources/cards/one_night_in_karazhan/minion_nightbane_templar.json
- cards/src/main/resources/cards/the_old_gods/rogue/spell_bloodthistle_toxin.json
- game/src/main/java/net/demilich/metastone/game/spells/CardCostModifierSpell.java
- game/src/main/java/net/demilich/metastone/game/spells/ReturnMinionToHandSpell.java
- Fixed a bug with Mana Modifiers and minions returning to hand.
- Fixed a few card bugs.
- Fixes #237 (Technically, not true, but unfortunately, there won't be any updates to the 2nd issue listed.)
> Fixed Mana Cost Modifier Bugs

- cards/src/main/resources/cards/the_old_gods/hunter/minion_giant_sand_worm.json
- cards/src/main/resources/cards/the_old_gods/neutral/minion_the_boogeymonster.json
- Now working as intended.
- Fixed #207
> Fixed Giant Sandworm and the Boogeymonster

- app/src/main/java/net/demilich/metastone/gui/playmode/HeroToken.java
- app/src/main/java/net/demilich/metastone/gui/playmode/PlayModeView.java
- app/src/main/resources/fxml/PlayModeView.fxml
- app/src/main/resources/fxml/SandboxModeView.fxml
- It might not look pretty, but Metastone now has a back button in Play Mode. This may or may not have been borrowed from Sandbox Mode... (Fixes #3)
- Hid secrets of player's with hidden cards. (Fixes #231)
> Hid Secrets and added Back Button

- game/src/main/java/net/demilich/metastone/game/spells/SummonOneOneCopySpell.java
- Added board position checking in SummonOneOneCopySpell (Fixes #249)
> Fixed Barnes

- app/src/main/java/net/demilich/metastone/gui/playmode/GameBoardView.java
- app/src/main/java/net/demilich/metastone/gui/playmode/GameToken.java
- app/src/main/java/net/demilich/metastone/gui/playmode/HeroToken.java
- app/src/main/java/net/demilich/metastone/gui/playmode/MinionToken.java
- app/src/main/resources/fxml/HeroToken.fxml
- Hero Power costs are now visible.
> Added adjustable Hero Power costs

- cards/src/main/resources/cards/basic/shaman/spell_rockbiter_weapon.json
- cards/src/main/resources/cards/basic/warrior/spell_charge.json
- cards/src/main/resources/cards/basic/warrior/spell_execute.json
- cards/src/main/resources/cards/classic/neutral/minion_abusive_sergeant.json
- cards/src/main/resources/cards/one_night_in_karazhan/minion_violet_illusionist.json
- cards/src/main/resources/cards/the_grand_tournament/shaman/minion_tuskarr_totemic.json
- cards/src/main/resources/cards/the_old_gods/hunter/spell_call_of_the_wild.json
- game/src/main/java/net/demilich/metastone/game/spells/CastRandomSpellSpell.java
- Added proposed card nerfs.
- Fixed Violet Illusionist.
> Card Nerfs

- app/src/main/java/net/demilich/metastone/gui/playmode/HeroToken.java
- game/src/main/java/net/demilich/metastone/game/spells/aura/Aura.java
- game/src/test/java/net/demilich/metastone/tests/CardInteractionTests.java
- Fixed Aura bugs by making sure triggers actually applied.
- Updated a test to use a card other than Charge. (Fixes #259)
- Fixed a bug with Secrets (Somewhat unrelated, but annoying.)
> Fixed Card Tests

- app/src/main/java/net/demilich/metastone/gui/playmode/HeroToken.java
> Added Hero Power and Weapon Card Hovers

- game/src/main/java/net/demilich/metastone/game/cards/Card.java
- Deck Builder now parses the search bar better.
- Added searchable tags: attack, mana, health (>,<,=,<=,>=,!=)
- Added searching by race.
- Added searching names without special characters
- Added searching by class
> Added better card parsing

- cards/src/main/resources/cards/mean_streets_of_gadgetzan/neutral/minion_second-rate_bruiser.json
> Capitalize 'r' in Second-rate Bruiser

- cards/src/main/resources/cards/the_old_gods/neutral/token_tauren_slime.json
> Update base mana cost of WOTOG slime token

- cards/src/main/resources/cards/mean_streets_of_gadgetzan/shaman/spell_call_in_the_finishers.json
- cards/src/main/resources/cards/mean_streets_of_gadgetzan/shaman/token_murloc_razorgill.json
- game/src/test/java/net/demilich/metastone/tests/TheOldGodsTests.java
Also add test suite for WOTOG. Fixes #308
> Update Call in the Finishers to summon Murloc Razorgill tokens

- cards/src/main/resources/cards/mean_streets_of_gadgetzan/shaman/spell_call_in_the_finishers.json
- cards/src/main/resources/cards/mean_streets_of_gadgetzan/shaman/token_murloc_razorgill.json
- game/src/test/java/net/demilich/metastone/tests/TheOldGodsTests.java
I tried to reproduce a reported bug with Darkshire Councilman from #309 in this unit test. The test (and a play-through in sandbox mode) confirms Darkshire Councilman works as intended.
This PR depends upon on PR #316 getting merged
> Add a test for Darkshire Councilman interaction

- app/src/main/java/net/demilich/metastone/gui/deckbuilder/ImportDeckCommand.java
- app/src/main/java/net/demilich/metastone/gui/deckbuilder/importer/ImporterFactory.java
- app/src/main/java/net/demilich/metastone/gui/deckbuilder/importer/TempostormImporter.java
Created TempostormImporter that imports deck from tempostorm.com using JSON API www.tempostorm.com/api/decks/
ImporterFactory based on url given by user decides whether to use TempostormImporter or HearthPwnImporter
> Implement importing deck from tempostorm.com

- cards/src/main/resources/cards/classic/neutral/minion_alarm-o-bot.json
- cards/src/main/resources/cards/classic/neutral/minion_mogushan_warden.json
- cards/src/main/resources/cards/mean_streets_of_gadgetzan/hunter/token_piranha.json
- cards/src/main/resources/cards/mean_streets_of_gadgetzan/hunter/weapon_piranha_launcher.json
- cards/src/main/resources/cards/mean_streets_of_gadgetzan/neutral/minion_doppelgangster.json
- cards/src/main/resources/cards/mean_streets_of_gadgetzan/rogue/minion_gadgetzan_ferryman.json
- cards/src/main/resources/cards/one_night_in_karazhan/spell_protect_the_king.json
- cards/src/main/resources/cards/the_old_gods/neutral/minion_duskboar.json
- cards/src/main/resources/cards/the_old_gods/warlock/minion_chogall.json
Alarm-o-bot -> [Alarm-o-Bot](http://hearthstone.gamepedia.com/Alarm-o-Bot)
Dopplegangster -> [Doppelgangster](http://hearthstone.gamepedia.com/Doppelgangster)
Mogushan Warden -> [Mogu'shan Warden](http://hearthstone.gamepedia.com/Mogu%27shan_Warden)
Cho'Gall -> [Cho'gall](http://hearthstone.gamepedia.com/Cho%27gall)
Protect the King -> [Protect the King!](http://hearthstone.gamepedia.com/Protect_the_King!)
Gadgetzhan Ferryman -> [Gadgetzan Ferryman](http://hearthstone.gamepedia.com/Gadgetzan_Ferryman)
Dusk Boar -> [Duskboar](http://hearthstone.gamepedia.com/Duskboar)
Pirahna Launcher -> [Piranha Launcher](http://hearthstone.gamepedia.com/Piranha_Launcher)
Pirahna -> [Piranha](http://hearthstone.gamepedia.com/Piranha)
> Fix cards naming

- README.md
- cards/src/main/resources/cards/mean_streets_of_gadgetzan/shaman/token_murloc_razorgill.json
- cards/src/main/resources/cards/the_grand_tournament/druid/token_sabertooth_tiger.json
* "Tiger Form" name changed to "Sabertooth Tiger".
* Eclipse building now exactly specifies where to find the compiler options.
> A couple fixes

- app/src/main/java/net/demilich/metastone/gui/gameconfig/PlayerConfigView.java
- game/src/main/java/net/demilich/metastone/game/GameContext.java
- game/src/main/java/net/demilich/metastone/game/behaviour/FlatMonteCarlo.java
The old montecarlo didn't simulate each game from the current turn to the end of the game but only to the end of the current turn.
> Fix montecarlo behaviour

- game/src/test/java/net/demilich/metastone/tests/AdvancedMechanicTests.java
Actually, we should revert this, let me write a better one.
> Revert "Add discard and draw test"
